# Generated by Django 5.1.6 on 2026-02-28 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contribution",
            name="contribution_type",
            field=models.CharField(
                choices=[("tithe", "Tithe"), ("offering", "Offering")],
                default="tithe",
                max_length=20,
            ),
        ),
    ]
