# Generated by Django 5.1.6 on 2026-02-28 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_contribution_contribution_type"),
        ("members", "0002_alter_member_department_alter_member_ministry_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PayrollRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("staff_name", models.CharField(max_length=255)),
                ("role_title", models.CharField(blank=True, max_length=150)),
                ("gross_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("deductions", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("allowances", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("net_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("paid_at", models.DateField()),
                ("notes", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "church",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payroll_records",
                        to="churches.church",
                    ),
                ),
            ],
            options={
                "ordering": ["-paid_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "attendance_type",
                    models.CharField(
                        choices=[("service", "Service"), ("event", "Event"), ("children", "Children Check-in")],
                        default="service",
                        max_length=20,
                    ),
                ),
                ("attended_at", models.DateTimeField()),
                ("present", models.BooleanField(default=True)),
                ("notes", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "church",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="churches.church",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attendance_records",
                        to="dashboard.event",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attendance_records",
                        to="members.member",
                    ),
                ),
            ],
            options={
                "ordering": ["-attended_at"],
            },
        ),
    ]
