# Generated by Django 5.1.6 on 2026-02-28 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("churches", "0001_initial"),
        ("members", "0002_alter_member_department_alter_member_ministry_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberSectionNotes",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("households", models.TextField(blank=True)),
                ("baptism_membership_status", models.TextField(blank=True)),
                ("ministry_assignments", models.TextField(blank=True)),
                ("activity_timeline", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "church",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_section_notes",
                        to="churches.church",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "member section notes",
            },
        ),
    ]
